### PR TITLE
`nix run` is now `nix shell`

### PR DESCRIPTION
**Pull request by nrdxp**
A few months ago the nix developers changed the semantics of the `nix run` command. Now `nix shell` does what we want.

Without this PR applied, any-nix-shell breaks the `nix run` command by passing it, what are now, invalid flags.

### CODE REVIEW

**Comment by haslersn** [comment]
I don't have the new `nix` yet. Is this tested?

**Comment by nrdxp** [comment]
yeah, I'm using it right now via nrdxp/nixflk@2e6f10dc857c95472f2d6c302e324a24efa05e78. I simply patched the package until this gets merged. I haven't run into any issues so far. I believe `nix shell` is the same code path that `nix run` used to occupy so I doubt it changes anything at all.

**Comment by haslersn** [comment]
Did you also test with the commit b90891b11b6a581876680dbf815c07b973640c98 I pushed to your branch?

**Comment by nrdxp** [comment]
I'll make a new patch and report back in a bit.

**Comment by nrdxp** [comment]
Yeah, still working fine on my end.

**Pull request merged**
