### PR TITLE
Support `nix develop`

### LINKED ISSUE #12: `nix develop` (flake) support ?
Hello,

I'm switching my projects and use more and more flakes.
When I do `nix develop`, it starts a bash shell instead of continue to use my current shell on fish.

Do you think it's possible to use `any-nix-shell` so it works with `nix develop` ?

### PR DESCRIPTION
**Pull request by 9999years**
Closes #12

### CODE REVIEW

**Comment by haslersn** [comment]
Maybe we shouldn't set `IN_NIX_RUN=1` when using `nix develop`. I think we remove that environment variable once we entirely drop support for `nix run`.

**Comment by haslersn** [comment]
I think `nix develop` overrides `$SHELL`. Maybe we should set it by changing the command as follows:

```bash
--command env "SHELL=$(which "$which_shell")" "$which_shell"
```

**Comment by haslersn** [comment]
Please also change the README. I think we can remove any mention of `nix run` in the README as it's solely supported for backwards compatibility. So you could probably just replace `run` by `develop` in the README.

**Comment by 9999years** [comment]
I'll update the README but those other changes are out of scope here. Happy to explore them in a future issue/PR.

**Comment by haslersn** [comment]
For `nix-shell` we also set `$SHELL`, so that's not out of scope when supporting a new command.

**Comment by 9999years** [comment]
OK, how's ac71bea70e3565e06286f8d20360ddf8ba4a59cc look?

**Review by haslersn — APPROVED** [review]

**Comment by 9999years** [comment]
I wrote [`nix-your-shell`](https://github.com/MercuryTechnologies/nix-your-shell) instead.

**Pull request closed without merging**
